[project]
name = "for-nursery"
version = "0.1"
description = ""
authors = []
dependencies = [
    "Cython>=3.0.7",
    "fastapi>=0.109.0",
    "uvicorn[standard]>=0.25.0",
    "strawberry-graphql[fastapi]>=0.217.0",
    "gunicorn>=21.2.0",
    "psycopg[binary]>=3.1.16",
    "SQLAlchemy>=2.0.25",
    "pydantic>=2.5.3",
    "pydantic-settings>=2.1.0",
]

requires-python = ">=3.13,<3.14"
license = {text = "MIT"}
[tool.ruff]
exclude = [".venv", ".uv_cache"]

[tool.ruff.lint]
ignore = ["E501", "E203"]
select = ["E", "F", "W", "I", "B", "DJ", "RUF", "S"]
extend-ignore = ["RUF012"]
external = ["DFA001"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[tool.uv]
exclude-newer = "1 week"

[dependency-groups]
dev = [
    "bandit[toml]>=1.7.5",
    "Faker>=18.13.0",
    "pytest>=7.4.0",
    "pytest-postgresql>=5.0.0",
    "devtools[pygments]>=0.11.0",
    "ruff>=0.16.5",
    "ty>=0.0.77",
]
